#!/usr/bin/env python3
"""Isolated native Fine + tmux test. Never relies on HOME to isolate macOS data."""
import json
import os
from pathlib import Path
import subprocess
import tempfile
import time

REPO = Path(__file__).resolve().parents[1]
BRIDGE = Path.home() / '.smux/bin/tmux-bridge'
APP = REPO / '.build/debug/Fine'
CLI = REPO / '.build/debug/fine-cli'
real_socket = Path.home() / '.fine/control.sock'
real_inode = real_socket.stat().st_ino if real_socket.exists() else None

with tempfile.TemporaryDirectory(prefix='fine-e2e-', dir='/tmp') as directory:
    root = Path(directory)
    (root / 'myworld').mkdir()
    stub = root / 'myworld/ccv'
    stub.write_text('#!/bin/sh\nprintf "FINE_READY %s\\n" "$FINE_TAB_ID"\nexec cat\n')
    stub.chmod(0o755)
    config = root / 'smux'
    config.mkdir()
    (config / 'hostname').write_text('mac\n')
    (config / 'hosts').write_text('mac = mac\n')
    env = dict(os.environ, FINE_HOME=str(root), HOME=str(root), SHELL='/bin/zsh',
               CODEX_HOME=str(root/'.codex'), XDG_DATA_HOME=str(root/'.local/share'), ZDOTDIR=str(root),
               TMUX_BRIDGE_CONFIG=str(config), TMUX_BRIDGE_STATE=str(root/'bridge'),
               TMUX_BRIDGE_SOCKET=str(root/'tmux.sock'))
    for key in ('TMUX', 'TMUX_PANE', 'FINE_TAB_ID'):
        env.pop(key, None)
    env['PATH'] = str(BRIDGE.parent) + ':' + env['PATH']
    log = (root / 'app.log').open('w')
    app = subprocess.Popen([str(APP)], env=env, stdout=log, stderr=log)
    def call(args, source=None, check=True):
        local = dict(env)
        if source and source.startswith('fine:'):
            local['FINE_TAB_ID'] = source[5:]
        elif source:
            local['TMUX_PANE'] = source
        return subprocess.run([str(x) for x in args], env=local, capture_output=True, text=True, check=check)
    def fine(*args, source=None, check=True):
        return call([CLI] + list(args), source=source, check=check)
    def bridge(*args, source=None, check=True):
        return call([BRIDGE] + list(args), source=source, check=check)
    def wait_for(fn):
        last = None
        for _ in range(100):
            try:
                last = fn()
                if last:
                    return last
            except (subprocess.CalledProcessError, ValueError, FileNotFoundError):
                pass
            time.sleep(.1)
        raise RuntimeError('timed out waiting: ' + str(last) + '\n' + (root/'app.log').read_text()[-2000:])
    try:
        wait_for(lambda: (root/'.fine/control.sock').is_socket())
        ping = json.loads(fine('--json', 'ping').stdout)
        assert ping['pid'] == app.pid, 'CLI reached a different app'
        created = json.loads(fine('--json', 'new', '--harness', 'claude', '--model', 'default').stdout)
        tab = created['id'].lower()
        addr = 'fine:' + tab
        text = wait_for(lambda: (s if 'FINE_READY' in s else None) if (s := fine('read', tab, '5').stdout) else None)
        assert tab in text, 'FINE_TAB_ID missing from PTY'
        # Terminal input and screen capture, including literal --help text.
        fine('send', tab, '--help')
        wait_for(lambda: '--help' in fine('read', tab, '5').stdout)
        fine('keys', tab, 'Enter')
        assert fine('keys', tab, 'Enter', check=False).returncode != 0
        call(['tmux', '-f', '/dev/null', '-S', root/'tmux.sock', 'new-session', '-d', '-s', 'test', '-x', '220', '-y', '25', 'cat'])
        bridge('trust', addr, source='%0')
        bridge('read', addr, '10', source='%0')
        bridge('msg', addr, 'from-tmux', source='%0')
        landed = wait_for(lambda: (s if 'from-tmux' in s else None) if (s := bridge('read', addr, '10', source='%0').stdout) else None)
        bridge('keys', addr, 'Enter', source='%0')
        # Reverse trust generated by the first message: no explicit trust here.
        fine('read', '%0', '10', source=addr)
        fine('msg', '%0', 'from-Fine', source=addr)
        returned = fine('read', '%0', '10', source=addr).stdout
        assert 'from-Fine' in returned and addr in returned
        fine('keys', '%0', 'Enter', source=addr)
        assert (root/'.fine/window-states.json').exists()
        assert real_inode is None or real_socket.stat().st_ino == real_inode, 'live Fine socket changed'
        evidence = {'isolated_home': str(root), 'app_pid': app.pid, 'tab': addr,
                    'screen_read': bool(text), 'pty_environment': tab in text,
                    'tmux_to_fine': 'from-tmux' in landed, 'fine_to_tmux': 'from-Fine' in returned,
                    'read_guard_consumed': True, 'live_socket_preserved': True}
        output = Path(__file__).resolve().parents[3] / '.smux/state/homenet/fine-isolated-e2e.json'
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(evidence, indent=2))
        print(json.dumps(evidence, indent=2))
    finally:
        call(['tmux', '-S', root/'tmux.sock', 'kill-server'], check=False)
        app.terminate()
        try: app.wait(timeout=5)
        except subprocess.TimeoutExpired:
            app.kill(); app.wait()
        log.close()
